[project]
name = "20260910-challenge-tables"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=3.0.5",
    "storage",
    "transformer-lens>=3.8.1",
]

[tool.uv.sources]
storage = { path = "../storage", editable = true }
